name: Firmware build

on:
  push:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@main
        with:
          app-path: firmware
          toolchains: riscv64-zephyr-elf

      - name: Set a timestamp variable
        shell: bash
        run: |
          echo "ESP_SHA=$(west list -f '{revision}' hal_espressif)" >> $GITHUB_ENV

      - name: Cache blobs
        uses: actions/cache@v4
        with:
          path: modules/hal/espressif/zephyr/blobs
          key: ccache-esp-blobs-${{ env.ESP_SHA }}

      - name: Fetch the blobs
        run: |
          west blobs fetch -a

      - name: Build
        run: |
          west build firmware
